

CREATE TABLE [dbo].[ORDER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDER_DATE] [datetime] NOT NULL,
	[ORDER_NUMBER] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ORDER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORDER] ADD  CONSTRAINT [DF_ORDER_ORDER_DATE]  DEFAULT (getdate()) FOR [ORDER_DATE]
GO

ALTER TABLE [dbo].[ORDER] ADD  CONSTRAINT [DF_ORDER_ORDER_NUMBER]  DEFAULT ('') FOR [ORDER_NUMBER]
GO



CREATE TABLE [dbo].[ORDER_ITEM](
	[ID] [int] NOT NULL,
	[ORDER_ID] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[UNIT_PRICE] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_ORDER_ITEM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORDER_ITEM] ADD  CONSTRAINT [DF_ORDER_ITEM_ORDER_ID]  DEFAULT ((0)) FOR [ORDER_ID]
GO

ALTER TABLE [dbo].[ORDER_ITEM] ADD  CONSTRAINT [DF_ORDER_ITEM_QUANTITY]  DEFAULT ((0)) FOR [QUANTITY]
GO

ALTER TABLE [dbo].[ORDER_ITEM] ADD  CONSTRAINT [DF_ORDER_ITEM_UNIT_PRICE]  DEFAULT ((0)) FOR [UNIT_PRICE]
GO



